name: TallTreePhotography
favicon: null
layout_spectrum: 1
typography_spectrum: 0.47021
title: Tall Tree Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#283348'
    - '#4b5771'
    - '#777c91'
    - '#cf9c6f'
    - '#845a20'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
