name: TallTreePhotography
favicon: null
layout_spectrum: 1
typography_spectrum: 0.66101
title: Photos by Travis Mercier
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ccab79'
    - '#f7faf1'
    - '#221b15'
    - '#956f5f'
    - '#1fc1b4'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
