name: TallTreePhotography
favicon: null
layout_spectrum: 0.51096
typography_spectrum: 0.70537
title: Photos by Travis Mercier
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6c6366'
    - '#060604'
    - '#fcc894'
    - '#df7752'
    - '#693317'
  brandStrength: 0
  lightness: 0.125
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
