name: TallTreePhotography
favicon: null
layout_spectrum: 1
typography_spectrum: 0.47021
title: Tall Tree Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#137fce'
    - '#070709'
    - '#b5d5f3'
    - '#eeafb1'
    - '#ae82b9'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
