name: TallTreePhotography
favicon: null
layout_spectrum: 0.51096
typography_spectrum: 0.70537
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1483d2'
    - '#060608'
    - '#b8d6f2'
    - '#273e5b'
    - '#ea736a'
  brandStrength: 0.8353405429515988
  lightness: 0.1875
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
